# 当前工作流名称
name: Deploy blog-ui
on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

# 构建任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    # 构建任务的步骤
    steps:
      # 切换分支
      - name: Checkout
      - uses: actions/checkout@v4

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}


#
#          script: |
#            cd /home/ubuntu/blog-ui
#            docker build -t ${{ secrets.DOCKER_REPOSITORY }} .
#            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
#            docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
#
#          script: |
#            docker stop blog-ui
#            docker container rm blog-ui
#            docker image rm ${{ secrets.DOCKER_REPOSITORY }}:latest -f | true
#            docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
#            docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
#            docker run -d -p 5000:80 --name blog-ui ${{ secrets.DOCKER_REPOSITORY }}
